### ISSUE TITLE
Change Title to "Eternity"

### ISSUE THREAD

**Issue by deadcoder0904** [eternityapp/extension#5]
Why did you put the title as "New Tab" rather than "Eternity"❓

https://github.com/eternityapp/extension/blob/c921f8fe594fdef0ac6a42c4e71077c32b4229b0/public/index.html#L27

**Comment by mubaris** [comment]
It was 'Eternity', but it was confusing people. Some users said they were unable to find where the empty tab was. 'New Tab' is the default chrome new tab title. Maybe, I'll change to `New Tab - Eternity`

**Comment by deadcoder0904** [comment]
But its not really a "New Tab", is it?

**Comment by mubaris** [comment]
Yep. This is a new tab without Eternity
![screenshot_1](https://user-images.githubusercontent.com/13871723/48255963-2e3d4600-e434-11e8-989a-7d80e5b8210e.png)
